### PR TITLE
fix: Detect Vaadin projects if dependencies are updated

### PR DESCRIPTION
**Pull request by MarcinVaadin**
Currently Vaadin dependencies were detected only on post-startup activity. It might cause race condition between this event and indexed / refreshed module libraries.

This PR uses ModuleRootListener to detect library updates together with PostStartupActivity.

If project is indexed already by IntelliJ, ModuleRootListener is not triggered and PostStartupActivity detects Vaadin properly.
If new project is created, PostStartup happen before module is fully loaded with all dependencies and we need to use ModuleRootListener to detect Vaadin.

### CODE REVIEW

**Comment by czp13** [comment]
1. Created a new Spring Boot project.
2. Updated the `pom.xml` to include Vaadin.
3. Then, I saw the following popups:
image

4. The application started without any issues.

❓ I didn't see any specific message saying, "You have a Vaadin project, Vaadin plugin enabled," or something similar. I expected to, but it's probably fine this way.

**Review by czp13 — COMMENTED** [review]
1. Created a new Spring Boot project.
2. Updated the `pom.xml` to include Vaadin.
3. Then, I saw the following popups:
image

4. The application started without any issues.

❓ I didn't see any specific message saying, "You have a Vaadin project, Vaadin plugin enabled," or something similar. I expected to, but it's probably fine this way.

So not sure where I could see, or check this log message:
```
   LOG.info("Vaadin detected in dependencies of " + event.project.name)
```

**Comment by MarcinVaadin** [comment]
@czp13 If you see those popups it means plugin has started because Vaadin project has been detected. So it's ok.

**Comment by czp13** [comment]
> @czp13 If you see those popups it means plugin has started because Vaadin project has been detected. So it's ok.

Okey,thanks :), then I will approve it if soonish no one else approves.

**Review by mgarciavaadin — APPROVED** [review]
Tested with the weirdest project structures I could imagine and working perfectly. Good Job!

**Pull request merged**
