### PR TITLE
Updated swap icons

### PR DESCRIPTION
**Pull request by anezthes**
## Description

Bettererer icons.

### CODE REVIEW

**Comment by MarcinVaadin** [comment]
image

That bug might be the same size as existing one

**Comment by MarcinVaadin** [comment]
https://plugins.jetbrains.com/docs/intellij/icons-style.html#basic-shapes

**Comment by anezthes** [comment]
Updated accordingly.

**Comment by MarcinVaadin** [comment]
image

Much better!

**Review by MarcinVaadin — APPROVED** [review]

**Pull request merged**
