### PR TITLE
chore: update plugin to use new intellij platform api

### PR DESCRIPTION
**Pull request by MarcinVaadin**
## Description

Use latest intellij platform 2.0.0 api

### CODE REVIEW

**Comment by czp13** [comment]
Tested with `2023.3.4` IntelliJ version and `undo`, `redo` only worked from the IntelliJ, not from the UI (Copilot activated).
I will upgrade to the latest Intellij and try again.

**Comment by czp13** [comment]
I tried again, not working from the _browser (I tried so far with Flow application)._ 


Retried with Hilla application, and works with _IntelliJ IDEA 2024.2 (Ultimate Edition)_, both redo and undo works for me, latest IntelliJ, and Hilla app.

**Review by czp13 — APPROVED** [review]
Hilla application works with latest IntelliJ (IntelliJ IDEA 2024.2 (Ultimate Edition).
Flow applications does not work for me.
(browser redo and undo)

**Comment by MarcinVaadin** [comment]
> Flow applications does not work for me.
(browser redo and undo)

Yes, known issue

**Pull request merged**
